### ISSUE TITLE
Question about save_now logic

### ISSUE THREAD

**Issue by bstriner** [inferno-pytorch/inferno#99]
I think there is a logic bug is save_now. Please correct me if I am wrong.

https://github.com/inferno-pytorch/inferno/blob/master/inferno/trainers/basic.py#L484

The second condition is currently:
```
elif self._is_iteration_with_best_validation_score:
            return self._save_at_best_validation_score
```

Shouldn't that be:
```
elif self._save_at_best_validation_score:
            return self._is_iteration_with_best_validation_score
```

If you are only saving at the best score, then only save_now if you are the best score.

However, if you are currently at the best score and save at best is off, it will not save. Should be an easy fix just swapping those two variables.

**Comment by constantinpape** [comment]
I think you are right, there is a logic issue in the current implementation.
But your proposed change would not fix this.
Note that the `_save_at_best_validation_score` does not mean that checkpoints should ONLY be made when the validation score, but that checkpoints should be made ALSO when the validation score is best. The change you have proposed would completely prevent saving if the validation score is not best. In the current implementation, a checkpoint that should be saved is only skipped in 
cases where `self._is_iteration_with_best_validation_score = True` and `self._save_at_best_validation_score = False`.

I think this issue could be fixed by removing the else block here:
https://github.com/inferno-pytorch/inferno/blob/master/inferno/trainers/basic.py#L486-L498

But @nasimrahaman should have a look at this before we change anything.

**Comment by bstriner** [comment]
@constantinpape That actually is what i thought "save_at_best_validation_score" meant (only save if it is the best).

If it should be both, then it should be:

elif self._is_iteration_with_best_validation_score and self._save_at_best_validation_score:
  return True

**Comment by constantinpape** [comment]
Yes, that should also work.

**Comment by bstriner** [comment]
Just submitted PR with the fix: https://github.com/inferno-pytorch/inferno/pull/100
